### ISSUE TITLE
Add Void1, Void2, ... VoidN

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [joneshf/purescript-void#5]
I would be useful to have additional phantom types.

```
newtype Void1 a = Void1 Void
newtype Void2 a b = Void2 Void
newtype Void3 a b c = Void3 Void
-- up to some N
```

So that they can be used in places where types of kinds other than `*` are expected, such as Halogen queries: `Component State Void1 t`.

However I am not sure if this would also require additional `coerce1..N` and `absurd1..N` functions or whether the existing ones could be made polymorphic.

**Comment by joneshf** [comment]
I'm not sure either. Could type aliases solve this instead of newtypes? Or is that too unsafe for what you'd want? I think that would allow the `coerce`/`absurd`s to remain the same. If not, might a typeclass be able to unify them?

**Comment by no-longer-on-githu-b** [comment]
Type aliases can't be partially applied, which would make this much less useful.

**Comment by joneshf** [comment]
Wait, seriously?!? When did that change?

**Comment by paf31** [comment]
It's been that way since synonyms were added, I think.

**Comment by no-longer-on-githu-b** [comment]
Const Void is a thing, which is sufficient.

May want to consider adding Const2 and Const3 at some point but I've never needed that.
